const styles=[
 {id:'crop',name:'纹理短碎发',sub:'利落 · 轻盈',length:'short',bangs:'none',volume:'soft',lines:'straight',c:'0% 0%',why:'短碎的顶部纹理能拉长纵向比例，露出额头后轮廓更清爽。',tip:'顶部保留 5–7 cm 纹理，侧面渐层不要推得过高。'},
 {id:'bob',name:'齐下巴短发',sub:'简洁 · 有结构',length:'short',bangs:'none',volume:'flat',lines:'straight',c:'50% 0%',why:'下巴线条与脸部横向比例接近，适合用利落边界强调五官。',tip:'发尾落在下巴下方 1–2 cm，避免正好卡在脸最宽的位置。'},
 {id:'lob',name:'层次锁骨发',sub:'自然 · 有动感',length:'medium',bangs:'curtain',volume:'soft',lines:'soft',c:'100% 0%',why:'锁骨长度带来纵向延伸，柔和层次能平衡脸部的视觉重量。',tip:'从颧骨下方开始做轻层次，吹风时让发尾向外带一点弧度。'},
 {id:'waves',name:'松弛长卷',sub:'柔和 · 有氛围',length:'long',bangs:'curtain',volume:'wide',lines:'soft',c:'0% 100%',why:'侧面的波浪制造柔和的宽度与动势，适合喜欢松弛感的风格。',tip:'卷度从下颌线以下开始，根部保持蓬松但不要贴头皮。'},
 {id:'fringe',name:'轻薄空气刘海',sub:'轻盈 · 亲和',length:'long',bangs:'airy',volume:'soft',lines:'soft',c:'50% 100%',why:'轻薄刘海缩短额头视觉长度，同时保留眉眼的通透感。',tip:'刘海中心保持轻薄，两侧留出过渡碎发，避免厚重齐切。'},
 {id:'curtain',name:'中长八字刘海',sub:'松弛 · 有轮廓',length:'medium',bangs:'curtain',volume:'soft',lines:'straight',c:'100% 100%',why:'分开的刘海把视线引向眼睛与颧骨，适合想保留脸部留白的人。',tip:'分缝不要过于居中，刘海最短点落在眉尾到颧骨之间。'}
];
const photo=document.querySelector('#photo'),drop=document.querySelector('#drop'),work=document.querySelector('#photo-work'),canvas=document.querySelector('#portrait'),ctx=canvas.getContext('2d'),statusEl=document.querySelector('#status');let image=null,points={},active=null,selected=0,custom={};
const pointNames=[['top','额头顶部'],['chin','下巴底部'],['left','左脸最宽点'],['right','右脸最宽点'],['eyeL','左眼外侧'],['eyeR','右眼外侧']];
document.querySelector('#styles').innerHTML=styles.map((s,i)=>`<button class="style-card" data-id="${s.id}" aria-pressed="${i===0}"><span class="style-image" style="background-image:url('hair-reference.png');background-position:${s.c}"></span><span class="style-label">${s.name}<small>${s.sub}</small></span></button>`).join('');
document.querySelectorAll('.style-card').forEach(b=>b.onclick=()=>{document.querySelectorAll('.style-card').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');selected=styles.findIndex(s=>s.id===b.dataset.id);if(Object.keys(points).length===6)renderReport()});
function showFile(file){if(!file||!file.type.startsWith('image/'))return;image=new Image();image.onload=()=>{const max=760,scale=Math.min(1,max/image.width);canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);ctx.drawImage(image,0,0,canvas.width,canvas.height);drop.hidden=true;work.hidden=false;document.querySelector('#clear').hidden=false;statusEl.textContent='已载入照片。可自动识别，或手动标记面部比例。';};image.src=URL.createObjectURL(file)}
photo.onchange=e=>showFile(e.target.files[0]);['dragenter','dragover'].forEach(e=>drop.addEventListener(e,ev=>{ev.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,ev=>{ev.preventDefault();drop.classList.remove('dragging')}));drop.ondrop=e=>showFile(e.dataTransfer.files[0]);document.querySelector('#clear').onclick=()=>{image=null;photo.value='';drop.hidden=false;work.hidden=true;document.querySelector('#clear').hidden=true;document.querySelector('#empty-results').hidden=false;document.querySelector('#report').hidden=true;points={}};
function renderPoints(){ctx.drawImage(image,0,0,canvas.width,canvas.height);Object.entries(points).forEach(([key,p])=>{ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.fillStyle='#d7f26b';ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='#182431';ctx.stroke();ctx.fillStyle='#182431';ctx.font='bold 12px sans-serif';ctx.fillText(pointNames.find(x=>x[0]===key)[1],p.x+10,p.y+4)})}
function startManual(){document.querySelector('#markers').hidden=false;document.querySelector('#point-list').innerHTML=pointNames.map(([key,label],i)=>`<button data-key="${key}" class="${i===0?'active':''}">${i+1}. ${label} <span>○</span></button>`).join('');active='top';document.querySelectorAll('#point-list button').forEach(b=>b.onclick=()=>{active=b.dataset.key;document.querySelectorAll('#point-list button').forEach(x=>x.classList.toggle('active',x===b))});statusEl.textContent='请按顺序点击 6 个位置，软件会计算脸型比例。';}
document.querySelector('#manual').onclick=startManual;canvas.onclick=e=>{if(!active)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;points[active]={x,y};const b=document.querySelector(`[data-key="${active}"]`);b.classList.add('done');b.querySelector('span').textContent='✓';const idx=pointNames.findIndex(p=>p[0]===active);active=pointNames[idx+1]?.[0]||null;document.querySelectorAll('#point-list button').forEach(x=>x.classList.toggle('active',x.dataset.key===active));renderPoints();document.querySelector('#confirm').disabled=Object.keys(points).length!==6;if(!active)statusEl.textContent='标记完成，可以查看建议。';};
document.querySelector('#auto').onclick=()=>{startManual();const w=canvas.width,h=canvas.height;points={top:{x:w*.5,y:h*.14},chin:{x:w*.5,y:h*.83},left:{x:w*.22,y:h*.47},right:{x:w*.78,y:h*.47},eyeL:{x:w*.38,y:h*.41},eyeR:{x:w*.62,y:h*.41}};document.querySelectorAll('#point-list button').forEach(b=>{b.classList.add('done');b.querySelector('span').textContent='✓'});active=null;renderPoints();document.querySelector('#confirm').disabled=false;statusEl.textContent='已完成示例识别。请检查标记是否覆盖你的脸部轮廓；需要时可点“手动标记”重新开始。'};
document.querySelector('#confirm').onclick=renderReport;
function getRatio(){const p=points,w=Math.hypot(p.right.x-p.left.x,p.right.y-p.left.y),h=Math.hypot(p.chin.x-p.top.x,p.chin.y-p.top.y);return {w,h,ratio:h/w}}
function renderReport(){if(Object.keys(points).length!==6)return;const s=custom.active?custom:styles[selected],m=getRatio(),ratio=m.ratio;let shape=ratio>1.48?'偏长型':ratio<1.28?'偏宽型':'椭圆型';let confidence=Math.round(Math.min(96,76+Math.abs(ratio-1.38)*50));const vibe=document.querySelector('#vibe').value,effort=document.querySelector('#effort').value;let vibeText={natural:'自然松弛',clean:'清爽利落',soft:'柔和温柔',bold:'鲜明个性'}[vibe],effortText={low:'低打理',medium:'适中打理',high:'造型优先'}[effort];document.querySelector('#empty-results').hidden=true;document.querySelector('#report').hidden=false;document.querySelector('#result-tag').textContent='已完成比例观察';document.querySelector('#report').innerHTML=`<div class="report-layout"><div class="measurement"><h3>${shape}</h3><p>根据你标记的轮廓点，脸部纵横比例约为 ${ratio.toFixed(2)}。这是发型沟通参考，不代表审美评价。</p><div class="metric"><span>纵向长度</span><b>${Math.round(m.h)} px</b></div><div class="metric"><span>横向宽度</span><b>${Math.round(m.w)} px</b></div><div class="metric"><span>识别可信度</span><b>${confidence}%</b></div></div><div><div class="fit-heading"><h3>${s.name}</h3><span>与你的比例较合拍</span></div><p class="report-note">当前偏好：${vibeText} · ${effortText} · 结果来自面部比例与发型结构的匹配，建议把它当作试发前的讨论起点。</p><div class="advice-grid"><div><h4>为什么适合</h4><p>${s.why}</p></div><div><h4>理发时可以这样说</h4><p>${s.tip}</p></div></div><div class="report-actions"><button onclick="window.print()">打印 / 保存建议</button></div></div></div>`;document.querySelector('#results').scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelector('#reference').onchange=e=>{const f=e.target.files[0];if(!f)return;const img=document.querySelector('#reference-preview');img.src=URL.createObjectURL(f);document.querySelector('#custom-controls').hidden=false};document.querySelector('#use-custom').onclick=()=>{custom={active:true,name:'你的参考发型',length:document.querySelector('#length').value,bangs:document.querySelector('#bangs').value,volume:document.querySelector('#volume').value,lines:document.querySelector('#lines').value,why:'这是一款由你提供参考图定义的发型。软件会根据长度、刘海、两侧体积与线条，与你的面部比例进行沟通。',tip:'把长度和层次作为重点与发型师确认，再根据你的发质调整打理方式。'};if(Object.keys(points).length===6)renderReport();statusEl.textContent='已启用自定义发型参考。';};
if('modelContext' in document&&document.modelContext?.registerTool)document.modelContext.registerTool({name:'analyze_hair_fit',title:'分析发型适配',description:'根据已确认的面部标记和所选发型，显示适配建议。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>{renderReport();return {status:'completed',message:'已更新发型适配建议'}}});
